# Generated by Django 2.1.1 on 2018-09-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email Address')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('image', models.CharField(max_length=200, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Peoples',
                'ordering': ['-name'],
            },
        ),
    ]
